[package]
name = "streaming-service"  # Should match this
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
anchor-lang = "0.31.0"
solana-program = "1.18.26"

[features]
idl-build = ["anchor-lang/idl-build"]